name: Deploy Lambda Using Cloud Formation

on:
 workflow_dispatch:
 
env:
  AWS_REGION: us-east-1  # Replace with your desired AWS region

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Set up Python
      uses: actions/setup-python@v3
      with:
         python-version: '3.13'
    
    - name: Install dependencies
      run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt -t ./deployment/package

    - name: Zip Lambda Function
      run: |
          cp lambda_function.py deployment/package/
          cd deployment/package
          zip -r ../../function.zip .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: ${{ env.AWS_REGION }}            
          
    - name: Upload Lambda package to S3
      run: |
        aws s3 cp function.zip s3://my-lambda-deployment-bucket-yaron/function.zip

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy --template-file cloudformation-template.yaml --stack-name MyLambdaStack

    - name: Handle Deployment Error
      if: failure()  # This step will run only if the previous step fails
      run: |   
        aws cloudformation describe-stack-events --stack-name MyLambdaStack
