name: Deploy Lambda

on:
 workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Zip Lambda Function
      run: |
          cp lambda_function.py deployment/package/
          cd deployment/package
          zip -r ../../function.zip .

    - name: Upload Lambda package to S3
      run: |
        aws s3 cp function.zip s3://my-lambda-deployment-bucket-yaron/function.zip
      env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET }}
          aws_region: us-east-1

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \\
          --template-file cloudformation-template.yaml \\
          --stack-name MyLambdaStack \\
          --capabilities CAPABILITY_NAMED_IAM
      env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET }}
          aws_region: us-east-1
